version: '3.8'

services:
 redis:
  image: redis
  container_name: redis

 frontend:
  image: example-frontend14
  ports: 
   - 5000:5000
  container_name: example-frontend-part2.4

 backend:
  image: example-backend14
  ports:
   - 8080:8080
  environment:
   - REDIS_HOST=redis
  container_name: example-backend-part2.4
