version: '3.8'

services:
  nginx:
    image: nginx:stable
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    depends_on:
      - frontend
      - backend
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db_postgres
  redis:
    image: redis
    container_name: redis2.10
  frontend:
    image: example-frontend14
    ports:
      - 5000:5000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost/api
    container_name: frontend2.10
  backend:
    image: example-backend14
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: backend2.10

volumes:
  database: