version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    container_name: db_postgres
  redis:
    image: redis
    container_name: redis2.9
  frontend:
    image: example-frontend14
    ports:
      - 5000:5000
    container_name: frontend2.9
  backend:
    image: example-backend14
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: backend2.9

volumes:
  database: